uuid = "00000000-0000-0000-0000-000000000001"
public_key = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
encrypted_secret_key = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
salt = "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
created_at = "2026-05-08T00:00:00Z"
is_password_protected = false
